#output: all.pdf, ROI.pdf, tran.pdf, rot.pdf
#
# - read mcflirt par files to see motion pulled out of simulation and original fMRI
#       [ ../qsub_possum4d.bash + ../restPreproc_possum.bash ]
# - read simulation motion input (psm.in)
#
# - calc frame displacment of of psm.in
# - read subj space per bb264ROI (noMotion - motion) difference in simulated fMRI after only motion correction
#    [ roidiffs/genDiffs.bash ]
#
# - plot everything :)


library(ggplot2)
library(reshape2)
library(plyr)
library(reshape2)
rm(list=ls())
# j* (or *) slice motion4D -- coreg and slicetiming -- use this to be empiraclly accurate
# m* mcflirt motion -- use this to stay consistant
##
## possum   t xyz meters , r xyz  radians
## mcflirt  r xyz radians, t xyz  m.meters
##  * need to take possum to mm (M.H. metioned degrees also?)
##  * need to put deg into mm before calc .3 
TR <- 2

motionfiles <- as.data.frame(rbind(
  # from simulation
  c('psm.NoMo', "nomotion/m_10895_nomot_roiAvg_fullFreq_1p9hold_possum_simt2_abs_trunc8.par"),
  c('psm.Mo'  , "fdM50/m_10895_fdM50pct_roiAvg_fullFreq_SHORT_2sTR_possum_simt2_abs_trunc8.par"),
  # from actual preprocessing
  c('org.Mo'  , "/Volumes/Phillips/Rest/Subjects/10761/rest/m_all.par")
))
names(motionfiles) <- c('ttl','file')

allmotion <- do.call("rbind",
 apply(motionfiles,1,
     function(x){
       mov      <- read.table(x[2])
       mov$time <- seq(TR,dim(mov)[1]*TR,by=TR)
       mov$ttl  <- x[1]
       mov
 })
)
names(allmotion)[1:6] <- paste( rep(c('rot','tran'),each=3), c('x','y','z'), sep="") 

############### input motion given to possum #############################################
# possum needed:
# http://fsl.fmrib.ox.ac.uk/fsl/fsl-4.1.9/possum/input.html#motion
#    the input motion sequence is defined in the simulator by an input file which specifies: 
#    time, Tx, Ty, Tz , Rx, Ry, Rz
#
#  time    in seconds
#  T*      characterising translations - in metres
#  R*      characterising rotations about the center of the volume - in radians
psm.in <- read.table("../defaults/motion_parameters/10761_motion_fdM_50pct")
names(psm.in) <- c("time", "tranx", "trany", "tranz", "rotx", "roty", "rotz") 
psm.in[,c('tranx','trany','tranz')] <- psm.in[,c('tranx','trany','tranz')] * 10^3
psm.in$ttl <- 'psm.in'

allmotion <-rbind(allmotion,psm.in)

# rework dataframe for graphing
m<-melt(allmotion,id.vars=c('time','ttl'))


# TODO: deal with different times?
#curious
#  ddply(allmotion, .(ttl), function(x){max(x$time)})
# are not all the same


##################################################################
## df thresh on what is fed to possum (psm.in)
mot.deriv <- colwise(function(col) c(0, diff(col)))(subset(allmotion,subset=ttl=='psm.in')[,1:6]) 
fd        <- subset(allmotion,subset=ttl=='psm.in',select=time)
fd$value  <- apply( mot.deriv[ , grepl('tran',names(mot.deriv)) ], 1, function(x) sum(    abs(x) ) ) + 
             apply( mot.deriv[ , grepl('rot' ,names(mot.deriv)) ], 1, function(x) sum( 50*abs(x) ) ) 
fd$variable <- 'fd.psm.in'
fd$ttl      <- 'fd.psm.in'


#MH: fd <- apply(mot.deriv[,1:3], 1, function(x) sum(2*pi*50*(abs(x)/360))) +  apply(mot.deriv[,4:6], 1, function(x) sum(abs(x)))
#    fd[1] <- NA
# MH:     mot.deriv <- colwise(function(col) c(0, diff(col)))(mot.raw) #Add 0 at beginning to maintain comparable dimension. raw vs. demean makes no difference in differencing

##################################################################
# load roi differences
#  raw difference of two possum simulations
#  264 rois w/rad of 5 (should match generation of possum)
#  * generated by roidiffs/genDiffs.bash
# -- column 1 is file (junk) 2 is time, rest selected by sample(1:264,10)

#ROIidx<-sample(1:264,10)
ROIidx<-c(2,181,172,189,80,19,229,105,174,123,55)
roiAvgs <- read.table(file='roidiffs/ROIdiff',header=T)[,ROIidx]
names(roiAvgs)<-sub('Mean_','ROI ',names(roiAvgs))
names(roiAvgs)[1]<-'time'

# reads in time as '#[?]' where # is the number of TRs. make this an actual number
#roiAvgs$time  <- as.numeric( sub('[?]','',roiAvgs$time,fixed=T) ) * TR
roiAvgs$time  <- seq(0,dim(roiAvgs)[1]-1) * TR

## facet for each roi
r<-melt(roiAvgs,id.vars=c('time'),variable.name='ttl')
r$variable='Difference'

## all roi's on one facet
#r<-melt(roiAvgs,id.vars=c('time','title'))
#roiAvgs$title <- 'ROI'



### ONE BIG GRAPH: all.pdf
plotdf <- rbind(fd,m,r)
#plotdf$title <- ifelse(grep('x|y|x',plotdf$variable),paste(sub('x|y|z','',plotdf$variable),plotdf$title,sep="_"),plotdf$title)
varvec <- grep('x|y|z',plotdf$variable)
plotdf$ttl[varvec] <- paste(sub('x|y|z','',plotdf$variable[varvec]),plotdf$ttl[varvec],sep=".")
# box above 0.3, 
p<-list()
p[['all']] <- ggplot(plotdf, aes(x=time,y=value,group=variable,color=variable))+geom_line()+theme_bw()+facet_grid(ttl~.,scales='free')
pdf('all.pdf',height=12)
print(p[['all']])
dev.off()



### GRAPH for each type: ROI.pdf, rot.pdf, tran.pdf
for(typ in c('ROI','rot','tran') ) {
 p[[typ]] <- ggplot(
	      subset(plotdf,grepl(typ,ttl)), 
	      aes(x=time,y=value,group=variable,color=variable)
	     )+
	     geom_line()+
	     theme_bw()+
	     facet_grid(ttl~.,scales='free')

 pdf(paste(typ,'.pdf',sep=""))
 print(p[[typ]])
 dev.off()
}


#p+geom <- rect(xmin=100,xmax=200,ymin=-Inf,ymax=+Inf,alpha=I(1),color=I(NULL),fill=I('blue'))

