library(ggplot2)
library(reshape2)
library(plyr)
library(reshape2)
rm(list=ls())
# j* (or *) slice motion4D -- coreg and slicetiming -- use this to be empiraclly accurate
# m* mcflirt motion -- use this to stay consistant
##
## possum   t xyz m, r xyz  r
## mcflirt  r xyz r, t xyz  mm
##  * need to take possum to deg and mm
##  * need to put deg into mm before calc .3 
TR <- 2
parfiles<-paste('nomotion',list.files(path='nomotion/',pattern='^m.*par'), sep='/');
parfiles<-c(parfiles, paste('fdM50',list.files(path='fdM50/',pattern='^m.*par'), sep='/') )
parfiles<-c(parfiles,'../defaults/motion_parameters/10761_motion_fdM_50pct')
parfiles<-c(parfiles,'/Volumes/Phillips/Rest/Subjects/10761/rest/m_all.par')

# remove the data.frame that is build iteratively if it already exists
if(exists('allmotion')) rm('allmotion')
# load motion from par and what is fed to possum
for (parfile in parfiles) { 
  motion <- read.table(parfile)
  ttl <- strsplit(parfile,'/')[[1]][1]
  if(ttl==""){ttl<-'10761'; TR<-1.5}
  if(grepl('par$',parfile)){
    # mcflirt par file is ordered:
    #  Rx Ry Rz Tx Ty Tz
    # in radians and mm
    # with a step for every TR (time = linenum*2), starting at the first TR
    # https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=ind1009&L=FSL&D=0&P=294004
    names(motion) <- paste( rep(c('rot','tran'),each=3), c('x','y','z'), sep="") 
    motion$time   <- seq(TR,dim(motion)[1]*TR, by=TR)
    TR<-2

  }
  else{
    ttl <- 'fed to possum'

    # possum needed:
    # http://fsl.fmrib.ox.ac.uk/fsl/fsl-4.1.9/possum/input.html#motion
    #    the input motion sequence is defined in the simulator by an input file which specifies: 
    #    time, Tx, Ty, Tz , Rx, Ry, Rz
    #
    #  time    in seconds
    #  T*      characterising translations - in metres
    #  R*      characterising rotations about the center of the volume - in radians
    names(motion)[1] <- 'time'

    names(motion)[2:7] <- paste( rep(c('tran','rot'),each=3), c('x','y','z'), sep="") 
    motion[5:7] <- motion[5:7] * 10^3
  }

  motion$title <- ttl
  if(exists('allmotion')) {
      allmotion <- rbind(allmotion, motion)
  }
  else {
      allmotion <- motion
  }
  motion <- motion[,c("rotx","roty","rotz","tranx","trany","tranz","time","title")]
  #print(head(subset(motion,time>16)))
}

m<-melt(allmotion,id.vars=c('time','title'))

## df thresh on what is fed to possum
mot.deriv <- colwise(function(col) c(0, diff(col)))(subset(allmotion,subset=title=='fed to possum')[,1:6]) 
fd        <- subset(allmotion,subset=title=='fed to possum',select=time)
fd$value  <- apply( mot.deriv[ , grepl('tran',names(mot.deriv)) ], 1, function(x) sum(    abs(x) ) ) + 
             apply( mot.deriv[ , grepl('rot' ,names(mot.deriv)) ], 1, function(x) sum( 50*abs(x) ) ) 
fd$variable <- 'fd'
fd$title    <- 'fd'


#Michael Hallquist: fd <- apply(mot.deriv[,1:3], 1, function(x) sum(2*pi*50*(abs(x)/360))) +  apply(mot.deriv[,4:6], 1, function(x) sum(abs(x)))
#    fd[1] <- NA
# Michael Hallquist:     mot.deriv <- colwise(function(col) c(0, diff(col)))(mot.raw) #Add 0 at beginning to maintain comparable dimension. raw vs. demean makes no difference in differencing

# load roi differences
#  raw difference of two possum simulations
#  264 rois w/rad of 5 (should match generation of possum)
#  * generated by roidiffs/genDiffs.bash
# -- column 1 is file (junk) 2 is time, rest selected by sample(1:264,10)
roiAvgs <- read.table(file='roidiffs/ROIdiff',header=T)[,c(2,181,172,189,80,19,229,105,174,123,55)]
names(roiAvgs)[1]<-'time'
names(roiAvgs)<-sub('Mean_','ROI ',names(roiAvgs))
# reads in time as '#[?]' where # is the number of TRs. make this an actual number
roiAvgs$time  <- as.numeric( sub('[?]','',roiAvgs$time,fixed=T) ) * TR

## all roi's on one facet
#r<-melt(roiAvgs,id.vars=c('time','title'))
#roiAvgs$title <- 'ROI'

## facet for each roi
r<-melt(roiAvgs,id.vars=c('time'),variable.name='title')
r$variable='Difference'

plotdf <- rbind(fd,m,r)
#plotdf$title <- ifelse(grep('x|y|x',plotdf$variable),paste(sub('x|y|z','',plotdf$variable),plotdf$title,sep="_"),plotdf$title)
varvec <- grep('x|y|z',plotdf$variable)
plotdf$title[varvec] <- paste(sub('x|y|z','',plotdf$variable[varvec]),plotdf$title[varvec],sep="_")
# box above 0.3, 
p<-list()
p[['all']] <- ggplot(plotdf, aes(x=time,y=value,group=variable,color=variable))+geom_line()+theme_bw()+facet_grid(title~.,scales='free')
pdf('all.pdf',height=12)
print(p[['all']])
dev.off()

for(typ in c('ROI','rot','tran') ) {
 p[[typ]] <- ggplot(subset(plotdf,grepl(typ,title)), aes(x=time,y=value,group=variable,color=variable))+geom_line()+theme_bw()+facet_grid(title~.,scales='free')
 pdf(paste(typ,'.pdf',sep=""))
 print(p[[typ]])
 dev.off()
}


#p+geom <- rect(xmin=100,xmax=200,ymin=-Inf,ymax=+Inf,alpha=I(1),color=I(NULL),fill=I('blue'))

