library(ggplot2)
library(reshape2)
#library(plyr)

# j* (or *) slice motion4D -- coreg and slicetiming -- use this to be empiraclly accurate
# m* mcflirt motion -- use this to stay consistant
##
## possum   t xyz m, r xyz  r
## mcflirt  r xyz r, t xyz  mm
##  * need to take possum to deg and mm
##  * need to put deg into mm before calc .3 
parfiles<-paste('nomotion',list.files(path='nomotion/',pattern='^m.*par'), sep='/');
parfiles<-c(parfiles, paste('fdM50',list.files(path='fdM50/',pattern='^m.*par'), sep='/') )
parfiles<-c(parfiles,'../defaults/motion_parameters/10761_motion_fdM_50pct')

# load motion from par and what is fed to possum
for (parfile in parfiles) { 
  motion <- read.table(parfile)
  ttl <- strsplit(parfile,'/')[[1]][1]
  if(grepl('par$',parfile)){
    # mcflirt outputs in trans first than rot
    names(motion) <- paste( rep(c('tran','rot'),each=3), c('x','y','z'), sep="") 
    motion$time   <- seq(2,dim(motion)[1]*2, by=2)
  }
  else{
    ttl <- 'fed to possum'
    # possum wanted (now have) rot, trans
    # is in meters instead of mm, fix that
    names(motion)[1] <- 'time'

    names(motion)[2:7] <- paste( rep(c('rot','tran'),each=3), c('x','y','z'), sep="") 
    motion[5:7] <- motion[5:7] * 10^3
  }

  motion$title <- ttl
  if(exists('allmotion')) {
      allmotion <- rbind(allmotion, motion)
  }
  else {
      allmotion <- motion
  }
}
m<-melt(allmotion,id.vars=c('time','title'))

## df thresh on what is fed to possum
mot.deriv <- colwise(function(col) c(0, diff(col)))(subset(allmotion,subset=ttl=='fed to possum')[,1:6]) 
fd        <- subset(allmotion,subset=ttl=='fed to possum',select=time)
fd$value  <- apply(mot.deriv[,1:3], 1, function(x) sum(abs(x))) + apply(mot.deriv[,4:6], 1, function(x) sum(50*(abs(x)))) 
fd$variable <- 'fd'
fd$title <- 'fd'


#Michael Hallquist: fd <- apply(mot.deriv[,1:3], 1, function(x) sum(2*pi*50*(abs(x)/360))) +  apply(mot.deriv[,4:6], 1, function(x) sum(abs(x)))
#    fd[1] <- NA
# Michael Hallquist:     mot.deriv <- colwise(function(col) c(0, diff(col)))(mot.raw) #Add 0 at beginning to maintain comparable dimension. raw vs. demean makes no difference in differencing

# load roi differences
#  raw difference of two possum simulations
#  264 rois w/rad of 5 (should match generation of possum)
#  * generated by roidiffs/genDiffs.bash
# -- column 1 is file (junk) 2 is time, rest selected by sample(1:264,10)
roiAvgs <- read.table(file='roidiffs/ROIdiff',header=T)[,c(2,181,172,189,80,19,229,105,174,123,55)]
names(roiAvgs)[1]<-'time'
names(roiAvgs)<-sub('Mean_','ROI ',names(roiAvgs))
roiAvgs$time  <- as.numeric( sub('[?]','',roiAvgs$time,fixed=T) ) * 2

## all roi's on one facet
#r<-melt(roiAvgs,id.vars=c('time','title'))
#roiAvgs$title <- 'ROI'

## facet for each roi
r<-melt(roiAvgs,id.vars=c('time'),variable.name='title')
r$variable='Difference'

# box above 0.3, 
p <- ggplot(rbind(fd,m,r),aes(x=time,y=value,group=variable,color=variable))+geom_line()+theme_bw()+facet_grid(title~.,scales='free')
#p+geom <- rect(xmin=100,xmax=200,ymin=-Inf,ymax=+Inf,alpha=I(1),color=I(NULL),fill=I('blue'))

